config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'library' => 'welcome#library'
  get 'contribute' => 'welcome#contribute'
  get 'about'  => 'welcome#about'

  get 'lesson/:id' => 'lessons#show'
  resources :lessons, except: [:update, :create, :destroy] do
    member do
      get 'propose_update'
    end
  end

  resources :lesson_versions do
    member do
    end
  end

  get 'media_contents' => 'media_contents#index'
  get 'media_contents/fields/:type' =>  'media_contents#fields'

  resources :courses do
    member do
      get 'viewing/:position', action: :viewing, as: :viewing
    end
  end

  resources :tracks do
    member do
      get 'viewing/:position', action: :viewing, as: :viewing
    end
  end

  resources :topics, only: [:index, :show]

  resources :programs, only: [:show]

  resources :teams, only: [:index, :show]

  namespace :moderate do
    get '/' => 'moderations#dashboard'
    get 'mytickets' => 'moderations#mytickets'
    get 'guides' => 'moderations#guides'
    get 'lessons' => 'lessons#index'
    get 'programs' => 'programs#index'
    get 'teams' => 'teams#index'
    get 'topics' => 'topics#index'
    get 'lesson_versions' => 'lesson_versions#index'
    get 'tracks' => 'tracks#index'
    get 'courses' => 'courses#index'
    get 'tickets' => 'tickets#index'
    get 'tickets/:id' => 'tickets#show', as: :ticket
  end
  post 'tickets/:id/claim' => 'moderate/tickets#claim', as: :claim_ticket
  post 'tickets/:id/unclaim' => 'moderate/tickets#unclaim', as: :unclaim_ticket
  post 'tickets/:id/subscribe' => 'moderate/tickets#subscribe', as: :subscribe_to_ticket
  post 'tickets/:id/unsubscribe' => 'moderate/tickets#unsubscribe', as: :unsubscribe_to_ticket
  post 'tickets/:id/assign_to/:user_id' => 'moderate/tickets#assign_to', as: :assign_ticket
  post 'tickets/:id/change_status/:state' => 'moderate/tickets#change_status', as: :change_ticket_status

  devise_for :users, path: 'auth', :controllers => { registrations: 'registrations' } , path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  get 'profile/:id' => 'profile#show', as: :user_profile
  get 'profile/:id/notifications' => 'profile#notifications', as: :user_notifications

end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :curated_items, -> { distinct }
  accepts_nested_attributes_for :curated_items, :reject_if => :all_blank, :allow_destroy => true
  validates :name, presence: true

  def self.default
    Program.find_by_name("General")
  end

  def self.search(search)
    Program.where("name LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%").distinct
  end

  def as_json(options={})
    super(:only => [:id, :name, :description]
    )
  end
end

app/controllers/moderate/programs_controller.rb
class Moderate::ProgramsController < ApplicationController
  def index
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def show
    @program = Program.find(params[:id])
  end
end

app/helpers/moderate/programs_helper.rb
module Moderate::ProgramsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
  def program_card(program)
    render partial: "programs/card", locals: { program: program }
  end

  def curated_item_card(curation)
    generalized_card(curation.curatable, curation.curatable_type)
  end

end

app/views/programs/_card.html.erb
<div class="bs-component">
  <div class="well well-lg highlight_card">
    <a href="<%= url_for program_path(program) %>">
      <% if program.cover_image_url %>
        <%= image_tag "#{program.cover_image_url}", class: "topic_img"%>
      <% else %>
        <h1><%= program.name %></h1>
      <% end %>
       <!--<img class="topic_img" src="/p/img/old/frc.gif">--></a>
    <p><%= program.description %></p>
  </div>
</div>

app/views/programs/show.html.erb
<% curation_type = "" %>
<% @program.curated_items.each do |curated_item| %>
<% if curated_item.curatable_type != curation_type %>
  <% if curation_type != "" %>
    </div>
  <% end %>
  <% curation_type = curated_item.curatable_type %>
  <div class="row">
      <h1 style="text-align: center" class="col-lg-offset-1"><%= curation_type %></h1>
<%end %>
  <div class="col-lg-5 col-lg-offset-1">
        <%= curated_item_card(curated_item) %>
  </div>
<% end %>
<% if curation_type != "" %>
  </div>
<% end %>