config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'library' => 'welcome#library'
  get 'contribute' => 'welcome#contribute'
  get 'about'  => 'welcome#about'

  get 'lesson/:id' => 'lessons#show'
  resources :lessons, except: [:update, :create, :destroy] do
    member do
      get 'propose_update'
    end
  end

  resources :lesson_versions do
    member do
    end
  end

  get 'media_contents' => 'media_contents#index'
  get 'media_contents/fields/:type' =>  'media_contents#fields'

  resources :courses do
    member do
      get 'viewing/:position', action: :viewing, as: :viewing
    end
  end

  resources :tracks do
    member do
      get 'viewing/:position', action: :viewing, as: :viewing
    end
  end

  resources :topics, only: [:index, :show]

  resources :programs, only: [:show]

  resources :teams, only: [:index, :show]

  namespace :moderate do
    get '/' => 'moderations#dashboard'
    get 'mytickets' => 'moderations#mytickets'
    get 'guides' => 'moderations#guides'
    get 'lessons' => 'lessons#index'
    get 'programs' => 'programs#index'
    get 'teams' => 'teams#index'
    get 'topics' => 'topics#index'
    get 'lesson_versions' => 'lesson_versions#index'
    get 'tracks' => 'tracks#index'
    get 'courses' => 'courses#index'
    get 'tickets' => 'tickets#index'
    get 'tickets/:id' => 'tickets#show', as: :ticket
  end
  post 'tickets/:id/claim' => 'moderate/tickets#claim', as: :claim_ticket
  post 'tickets/:id/unclaim' => 'moderate/tickets#unclaim', as: :unclaim_ticket
  post 'tickets/:id/subscribe' => 'moderate/tickets#subscribe', as: :subscribe_to_ticket
  post 'tickets/:id/unsubscribe' => 'moderate/tickets#unsubscribe', as: :unsubscribe_to_ticket
  post 'tickets/:id/assign_to/:user_id' => 'moderate/tickets#assign_to', as: :assign_ticket
  post 'tickets/:id/change_status/:state' => 'moderate/tickets#change_status', as: :change_ticket_status

  devise_for :users, path: 'auth', :controllers => { registrations: 'registrations' } , path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  get 'profile/:id' => 'profile#show', as: :user_profile
  get 'profile/:id/notifications' => 'profile#notifications', as: :user_notifications

end

app/views/shared/_extras.html.erb
<!-- Searchable Input Modal -->
<div class="modal fade" id="searchable-input-modal" tabindex="-1" role="dialog" aria-labelledby="searchable-input">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header silent-form">
        <div >
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="searchable-input">Seach and Insert</h4>
      </div>
        <form method="#" action="#"  novalidate id="searchable-input-form">
          <ul class="row list-inline" >
              <li class="form-group col-xs-9">
                <input class="form-control" type="text"  name="search" id="searchable-input-search" value="" placeholder="Search">
              </li>
              <li class="col-xs-3"><button type="submit" class="btn btn-primary btn-raised" id="searchable-input-submit">
               <i  class="material-icons" >search</i>Search</button></li>
          </ul>
          <div class="row-horizon scrollable" >
            <ul class="list-inline" id="searchable-input-filters"></ul>
          </div>
        </form>

        </div>

      <div class="modal-body">
        <div class="table-responsive" >
          <table class="table table-hover">
            <thead>
              <tr class="text-nowrap">
                <th class="col-xs-2">Select</th>
                <th class="col-xs-8">Preview</th>
                <th class="col-xs-2">Insert<br><small>Item</small></th>
              </tr>
            </thead>
            <tbody id="searchable-input-body">
            </tbody>
          </table>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary btn-raised" id="searchable-input-bulk-insert">Insert Selected</button>
      </div>
    </div>
  </div>
</div>
<!-- end Searchable Input Modal -->

app/views/shared/_footer.html.erb
<footer class="footer" role="contentinfo">
  <div class="container">

    <div class="col-lg-4">
      <div class="bs-component">
         <p>An open learning platform,<br/> for all things <a class='api-url' href="http://www.firstinspires.org/" target="_blank" >FIRST</a></p>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="bs-component">
      <p>&copy; 2015 - FIRSTMastery </p>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="bs-component">
      <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in? %>
        <li class="dropup"><a href="#" class="btn btn-warning btn-raised dropdown-toggle"
          id="notificationsMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          <span class='material-icons'>notifications</span></a>
          <ul class="dropdown-menu dropdown-menu-left shadowless " style="width:300px" aria-labelledby="notificationsMenue">
            <% current_user.user_feed_activities.last(5).each do |notification| %>
              <li><%= notification_card(notification) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <!-- General Notifications after this point -->
            <!-- TODO GROUP BY NOTIFICATION TYPE -->
            <% current_user.general_feed_activities.last(5).each do |notification| %>
              <li><%= general_notification_card(notification) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "See All", user_notifications_path(current_user) %></li>
          </ul>
        </li>
        <!-- if moderator -->
        <li><%= link_to raw("<span class='material-icons'>confirmation_number</span> Moderate"),
                moderate_path, class: "btn btn-info btn-raised" %></li>
        <!-- -->
        <li><%= link_to raw("<span class='fa fa-fw fa-user' ></span> Profile"),
                  user_profile_path(current_user.id), class: "btn btn-info btn-raised"%></li>
        <li><%= link_to raw("<span class='fa fa-fw fa-sign-out' ></span> Sign out"),
              destroy_user_session_path,
              :method => :delete, class: "btn btn-danger btn-raised"%></li>
      <% else %>
        <li><a class="btn btn-primary btn-raised" href="<%= url_for new_user_session_path %>"><span class="fa fa-fw fa-sign-in"></span> Sign in</a></li>
        <li class="divider"></li>
        <li><a class="btn btn-info btn-raised" href="<%= new_user_registration_path %>"><span class="fa fa-fw fa-chevron-up"></span> Sign up</a> </li>
      <% end %>
      </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_hamburger.html.erb
<!-- Sidebar -->
<nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
    <ul class="nav sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                FIRSTMastery
            </a>
        </li>
        <li>
            <a href="/">Home</a>
        </li>
        <li>
            <a href="/library">Library</a>
        </li>
        <li>
            <a href="/contribute">Contribute Content</a>
        </li>
        <li>
            <a href="#">Help</a>
        </li>
        <li>
            <a href="/about">About</a>
        </li>
        <li>
            <a href="/feedback">Feedback</a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Social<span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">FIRSTMastery on the web</li>
                <li>
                    <a style="padding: 2px 16px;" href="https://github.com/wilfriedE/FIRSTMastery">Github</a>
                </li>
                <!--<li><a style="padding: 2px 16px;" href="#">Twitter</a></li>
           <li><a style="padding: 2px 16px;" href="#">Facebook</a></li>
           <li><a style="padding: 2px 16px;" href="#">G+</a></li>
           <li><a style="padding: 2px 16px;" href="#">Youtube</a></li>-->
            </ul>
        </li>
    </ul>
</nav>
<!-- /#sidebar-wrapper -->

<!-- Hamburger-button -->
<button type="button" class="hamburger is-closed" data-toggle="offcanvas">
    <h5 style="margin-left: 36px;font-size: 28px;margin-top: 2px;">Menu</h5>
    <span class="hamb-top"></span>
    <span class="hamb-middle"></span>
    <span class="hamb-bottom"></span>
</button>
<!-- /#hamburger-button-->

app/views/shared/_notification_card.html.erb
<div class="row media well">
  <div class="media-body">
    <h4><strong><%= notification.name %></strong></h4>
    <p><%= notification.description %></p>
  </div>
</div>