config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'library' => 'welcome#library'
  get 'contribute' => 'welcome#contribute'
  get 'about'  => 'welcome#about'

  get 'lesson/:id' => 'lessons#show'
  resources :lessons, except: [:update, :create, :destroy] do
    member do
      get 'propose_update'
    end
  end

  resources :lesson_versions do
    member do
    end
  end

  get 'media_contents' => 'media_contents#index'
  get 'media_contents/fields/:type' =>  'media_contents#fields'

  resources :courses do
    member do
      get 'viewing/:position', action: :viewing, as: :viewing
    end
  end

  resources :tracks do
    member do
      get 'viewing/:position', action: :viewing, as: :viewing
    end
  end

  resources :topics, only: [:index, :show]

  resources :programs, only: [:show]

  resources :teams, only: [:index, :show]

  namespace :moderate do
    get '/' => 'moderations#dashboard'
    get 'mytickets' => 'moderations#mytickets'
    get 'guides' => 'moderations#guides'
    get 'lessons' => 'lessons#index'
    get 'programs' => 'programs#index'
    get 'teams' => 'teams#index'
    get 'topics' => 'topics#index'
    get 'lesson_versions' => 'lesson_versions#index'
    get 'tracks' => 'tracks#index'
    get 'courses' => 'courses#index'
    get 'tickets' => 'tickets#index'
    get 'tickets/:id' => 'tickets#show', as: :ticket
  end
  post 'tickets/:id/claim' => 'moderate/tickets#claim', as: :claim_ticket
  post 'tickets/:id/unclaim' => 'moderate/tickets#unclaim', as: :unclaim_ticket
  post 'tickets/:id/subscribe' => 'moderate/tickets#subscribe', as: :subscribe_to_ticket
  post 'tickets/:id/unsubscribe' => 'moderate/tickets#unsubscribe', as: :unsubscribe_to_ticket
  post 'tickets/:id/assign_to/:user_id' => 'moderate/tickets#assign_to', as: :assign_ticket
  post 'tickets/:id/change_status/:state' => 'moderate/tickets#change_status', as: :change_ticket_status

  devise_for :users, path: 'auth', :controllers => { registrations: 'registrations' } , path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  get 'profile/:id' => 'profile#show', as: :user_profile
  get 'profile/:id/notifications' => 'profile#notifications', as: :user_notifications

end

app/controllers/welcome_controller.rb
# The Welcome controller takes care of general pages.
class WelcomeController < ApplicationController
  def index
    @programs = Program.all
  end

  def library
      limit = 6
      @lessons = Lesson.offset(params[:lesson_pg].to_i * limit).first(limit)
      @courses = Course.offset(params[:course_pg].to_i * limit ).first(limit)
      @tracks = Track.offset(params[:track_pg].to_i * limit ).first(limit)
  end

  def contribute
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="row">
    <div class="bs-component">
      <div class="well well-lg">
        <h2> What's FIRSTMastery?</h2>
        <p>FIRSTMastery is an attempt to create a learning platform for FIRST community, where the community can submit learning materials as well as learn with the provided resources by others. The platform is built to allow flexibility in material source. Currently it primarily supports youtube videos and Vimeo videos. As the project development continues more material sources will be available such as embedable presentations, and or PDFs.</p>

        <h2> Learning Structure</h2>
        <p>There are Tracks, Courses and Lessons. The learning structure is provided an organized approach at learning.</p>
        <ul>
          <li><h5>Tracks</h5>
            <p>Tracks are a collection of courses. An example of a track is "FRC Pneumatics"</p>
          </li>
          <li><h5>Courses</h5>
            <p>Courses are a collection of lessons. An example of a course is "How to assemble your Pneumatic system."</p>
          </li>
          <li><h5>Lessons</h5>
            <p>Lessons are the lowest level in the learning structure. A lesson is an individualized lesson to learn one specific think. An example of a lesson is "Cutting the Pneumatic Tube."</p>
          </li>
        </ul>

        <h2 id="faq"> F.A.Q </h2>
        <ul>
          <li><h5>What types of learning contents can I add?</h5>
            <p>It can be a video on scouting at events, assembling the robot, writting a good business plan, etc... Generaly anything that could help the FIRST community grow.</p>
          </li>
          <li><h5>How can I help?</h5>
            <p>You can contibute learning materials, become a moderator, or contribute to our <a href="https://github.com/wilfriedE/FIRSTMastery">source code</a>.</p>
          </li>
          ...
        </ul>
      </div>
    </div>
</div>

app/views/welcome/contribute.html.erb
<div class="row">

  <div class="col-lg-4">
    <div class="bs-component">
      <div class="well well-lg highlight_card">
        <h2><a href="<%= url_for new_lesson_path %>"> Create a Lesson</a></h2>
        <p>Share a lesson with the FIRST community. An example lesson is "Using a clamp". (Try to make them short and to the point. If it needs more time we recommend creating a course and adding the various lessons as part of one course.) </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="bs-component">
      <div class="well well-lg highlight_card">
        <h2><a href="<%= url_for new_course_path %>">Create a Course</a></h2>
        <p>Agregate lessons to create a course. This would enable users to have good understanding of a good concept. Example of a course is "FTC Robot Parts"</p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="bs-component">
      <div class="well well-lg highlight_card">
        <h2><a href="<%= url_for new_track_path %>">Create a Track</a></h2>
        <p>Create a course track. Example of a track is 'Programming an FRC Robot'</p>
      </div>
    </div>
  </div>

</div>

<div class="row">

  <div class="col-lg-4">
    <div class="bs-component">
      <div class="well well-lg highlight_card">
        <h2>Become a moderator</h2>
        <p>Approve contents and help the community become a great place.</p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="bs-component">
      <div class="well well-lg highlight_card">
        <h2>Contribute on github :)</h2>
        <p>Help maintain the <a href="https://github.com/wilfriedE/FIRSTMastery">source code</a> and make this a better platform.</p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="bs-component">
      <div class="well well-lg highlight_card">
        <h2>TBD</h2>
        <p>TBD</p>
      </div>
    </div>
  </div>

</div>

app/views/welcome/index.html.erb
<div class="row">
    <% @programs.each do |program| %>
    
      <div class="col-lg-4">
        <%= program_card(program) %>
      </div>

    <% end %>

    <div class="col-lg-4">
      <div class="bs-component">
        <div class="well well-lg highlight_card">
          <h2><a href="/contribute">Contribute Materials</a></h2>
          <p>Help make this community better by contributing materials.</p>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="bs-component">
        <div class="well well-lg highlight_card">
          <h2><a href="/about">What's FIRSTMastery</a></h2>
          <p>Learn more about the FIRSTMastery project.</p>
        </div>
      </div>
    </div>
</div>

app/views/welcome/library.html.erb
<div class="row">
  <div class="well well-sm col-lg-offset-1" >
    <h3  style="text-align: center">Latest Materials</h3>
  </div>
</div>
<% if @lessons.count > 0 %>
<div class="row">
  <h1 style="text-align: center" class="col-lg-offset-1">Lesson</h1>
  <% @lessons.each do |lesson| %>
    <div class="col-lg-5 col-lg-offset-1">
          <%= lesson_card(lesson) %>
    </div>
  <%end %>
</div>
<% end %>

<% if @courses.count > 0 %>
<div class="row">
  <h1 style="text-align: center" class="col-lg-offset-1">Course</h1>
  <% @courses.each do |course| %>
    <div class="col-lg-5 col-lg-offset-1">
          <%= course_card(course) %>
    </div>
  <%end %>
</div>
<% end %>

<% if @tracks.count > 0 %>
<div class="row">
  <h1 style="text-align: center" class="col-lg-offset-1">Track</h1>
  <% @tracks.each do |track| %>
    <div class="col-lg-5 col-lg-offset-1">
          <%= track_card(track) %>
    </div>
  <%end %>
</div>
<% end %>